global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'user'
    static_configs:
      - targets: ['user:8082']
  - job_name: 'user-message-handler'
    static_configs:
      - targets: ['user-message-handler:8082']
  - job_name: 'user-workflow-worker'
    static_configs:
      - targets: ['user-workflow-worker:8082']
