services:
  payment:
    container_name: payment
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - service
    ports:
      - "8083:8081"
    environment:
      PAYMENT_DATABASE_HOST: payment-db
      PAYMENT_DATABASE_NAME: payment_db
      PAYMENT_DATABASE_USER: payment
      PAYMENT_DATABASE_PASSWORD: 12345Q
    depends_on:
      payment-db:
        condition: service_healthy
    networks:
      - common-net

  payment-workflow-worker:
    container_name: payment-workflow-worker
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - workflow-worker
    environment:
      PAYMENT_DATABASE_HOST: payment-db
      PAYMENT_DATABASE_NAME: payment_db
      PAYMENT_DATABASE_USER: payment
      PAYMENT_DATABASE_PASSWORD: 12345Q

      PAYMENT_TEMPORAL_HOST: temporal:7233
    depends_on:
      payment-db:
        condition: service_healthy
    networks:
      - common-net

  payment-message-handler:
    container_name: payment-message-handler
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      PAYMENT_DATABASE_HOST: payment-db
      PAYMENT_DATABASE_NAME: payment_db
      PAYMENT_DATABASE_USER: payment
      PAYMENT_DATABASE_PASSWORD: 12345Q

      PAYMENT_AMQP_HOST: rmq
      PAYMENT_AMQP_USER: guest
      PAYMENT_AMQP_PASSWORD: guest

      PAYMENT_TEMPORAL_HOST: temporal:7233
    depends_on:
      payment-db:
        condition: service_healthy
    networks:
      - common-net

  payment-db:
    image: "mysql:8.3"
    container_name: payment-db
    command: [ "--max_connections=100" ]
    volumes:
      - "payment-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: payment_db
      MYSQL_USER: payment
      MYSQL_PASSWORD: 12345Q
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s
    networks:
      - common-net

volumes:
  payment-db-data:

networks:
  common-net:
    external: true