apiVersion: v1
kind: Service
metadata:
  name: product
spec:
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
  selector:
    app: product
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      initContainers:
        - name: product-migrator
          image: product:latest
          imagePullPolicy: Never
          command: ["/app/product", "migrate"]
          env:
            - name: PRODUCT_DB_HOST
              value: mysql.infrastructure.svc.cluster.local
            - name: PRODUCT_DB_PORT
              value: "3306"
            - name: PRODUCT_DB_NAME
              value: product
            - name: PRODUCT_DB_USER
              value: product
            - name: PRODUCT_DB_PASSWORD
              value: 12345Q
      containers:
        - name: product
          image: product:latest
          imagePullPolicy: Never
          command: ["/app/product", "service"]
          ports:
            - containerPort: 8081
              name: grpc
          env:
            - name: PRODUCT_DB_HOST
              value: mysql.infrastructure.svc.cluster.local
            - name: PRODUCT_DB_PORT
              value: "3306"
            - name: PRODUCT_DB_NAME
              value: product
            - name: PRODUCT_DB_USER
              value: product
            - name: PRODUCT_DB_PASSWORD
              value: 12345Q
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-worker
  template:
    metadata:
      labels:
        app: product-worker
    spec:
      containers:
        - name: product-worker
          image: product:latest
          imagePullPolicy: Never
          command: ["/app/product", "worker"]
          env:
            - name: PRODUCT_DB_HOST
              value: mysql.infrastructure.svc.cluster.local
            - name: PRODUCT_DB_PORT
              value: "3306"
            - name: PRODUCT_DB_NAME
              value: product
            - name: PRODUCT_DB_USER
              value: product
            - name: PRODUCT_DB_PASSWORD
              value: 12345Q
            - name: PRODUCT_TEMPORAL_HOST
              value: temporal.infrastructure.svc.cluster.local:7233