apiVersion: v1
kind: Service
metadata:
  name: temporal
spec:
  ports:
    - name: frontend
      port: 7233
      targetPort: 7233
  selector:
    app: temporal
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal
  template:
    metadata:
      labels:
        app: temporal
    spec:
      containers:
        - name: temporal
          image: temporalio/auto-setup:1.29.1
          ports:
            - containerPort: 7233
              name: frontend
          env:
            - name: DB
              value: mysql8
            - name: MYSQL_PORT
              value: "3306"
            - name: DB_PORT
              value: "3306"
            - name: MYSQL_HOST
              value: mysql.infrastructure.svc.cluster.local
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_SEEDS
              value: mysql.infrastructure.svc.cluster.local
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: config/dynamicconfig/development-sql.yaml
          volumeMounts:
            - name: dynamic-config-vol
              mountPath: /etc/temporal/config/dynamicconfig
      volumes:
        - name: dynamic-config-vol
          configMap:
            name: temporal-dynamic-config
            items:
              - key: development-sql.yaml
                path: development-sql.yaml
      # --------------------------------
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: temporal-ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:2.34.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal.infrastructure.svc.cluster.local:7233
            - name: TEMPORAL_PORT
              value: "8080"