apiVersion: v1
kind: Secret
metadata:
  name: mysql-init-db
type: Opaque
stringData:
  # Формат: DB_NAME|USER|PASS (для скрипта инициализации)
  1-user: "user_db|user|12345Q"
  2-payment: "payment_db|payment|12345Q"
  3-order: "order_db|order|12345Q"
  4-product: "product|product|12345Q"
  # Notification использует payment_db (согласно docker-compose), но создадим отдельного юзера
  5-notification: "notification_db|notification|12345Q"  # Temporal DB
  6-temporal: "temporal|temporal|12345Q"
  7-temporal-visibility: "temporal_visibility|temporal|12345Q"