services:
  user:
    container_name: user
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - service
    ports:
      - "8081:8081"
    environment:
      USER_DATABASE_HOST: user-db
      USER_DATABASE_NAME: user_db
      USER_DATABASE_USER: user
      USER_DATABASE_PASSWORD: 12345Q
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - common-net

  user-workflow-worker:
    container_name: user-workflow-worker
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - workflow-worker
    environment:
      USER_DATABASE_HOST: user-db
      USER_DATABASE_NAME: userservice_db
      USER_DATABASE_USER: user
      USER_DATABASE_PASSWORD: 12345Q

      USER_TEMPORAL_HOST: temporal:7233
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - common-net

  user-message-handler:
    container_name: user-message-handler
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - message-handler
    environment:
      USER_DATABASE_HOST: user-db
      USER_DATABASE_NAME: userservice_db
      USER_DATABASE_USER: user
      USER_DATABASE_PASSWORD: 12345Q

      USER_AMQP_HOST: rmq
      USER_AMQP_USER: guest
      USER_AMQP_PASSWORD: guest

      USER_TEMPORAL_HOST: temporal:7233
    depends_on:
      user-db:
        condition: service_healthy
    networks:
      - common-net

  user-db:
    image: "mysql:8.3"
    container_name: user-db
    command: [ "--max_connections=100" ]
    volumes:
      - "user-db-data:/var/lib/mysql"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: userservice_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345Q
    healthcheck:
      test: mysql -h127.0.0.1 -uroot -e 'SELECT 1'
      interval: 10s
      timeout: 30s
    networks:
      - common-net

volumes:
  user-db-data:

networks:
  common-net:
    external: true