apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
    - name: http
      port: 8082
      targetPort: 8082
  selector:
    app: payment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      initContainers:
        - name: payment-migrator
          image: payment:latest
          imagePullPolicy: Never
          command: ["/app/payment", "migrate", "database"]
          env:
            - name: PAYMENT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PAYMENT_DATABASE_NAME
              value: payment_db
            - name: PAYMENT_DATABASE_USER
              value: payment
            - name: PAYMENT_DATABASE_PASSWORD
              value: 12345Q
      containers:
        - name: payment
          image: payment:latest
          imagePullPolicy: Never
          command: ["/app/payment", "service"]
          ports:
            - containerPort: 8081
              name: grpc
            - containerPort: 8082
              name: http
          env:
            - name: PAYMENT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PAYMENT_DATABASE_NAME
              value: payment_db
            - name: PAYMENT_DATABASE_USER
              value: payment
            - name: PAYMENT_DATABASE_PASSWORD
              value: 12345Q
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-worker
  template:
    metadata:
      labels:
        app: payment-worker
    spec:
      containers:
        - name: payment-worker
          image: payment:latest
          imagePullPolicy: Never
          command: ["/app/payment", "workflow-worker"]
          env:
            - name: PAYMENT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PAYMENT_DATABASE_NAME
              value: payment_db
            - name: PAYMENT_DATABASE_USER
              value: payment
            - name: PAYMENT_DATABASE_PASSWORD
              value: 12345Q
            - name: PAYMENT_TEMPORAL_HOST
              value: temporal.infrastructure.svc.cluster.local:7233
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-handler
  template:
    metadata:
      labels:
        app: payment-handler
    spec:
      containers:
        - name: payment-handler
          image: payment:latest
          imagePullPolicy: Never
          command: ["/app/payment", "message-handler"]
          env:
            - name: PAYMENT_DATABASE_HOST
              value: mysql.infrastructure.svc.cluster.local:3306
            - name: PAYMENT_DATABASE_NAME
              value: payment_db
            - name: PAYMENT_DATABASE_USER
              value: payment
            - name: PAYMENT_DATABASE_PASSWORD
              value: 12345Q
            - name: PAYMENT_TEMPORAL_HOST
              value: temporal.infrastructure.svc.cluster.local:7233
            - name: PAYMENT_AMQP_HOST
              value: rabbitmq.infrastructure.svc.cluster.local:5672
            - name: PAYMENT_AMQP_USER
              value: guest
            - name: PAYMENT_AMQP_PASSWORD
              value: guest